config/routes.rb
Rails.application.routes.draw do
  get 'profile/profile'

  get '/profile', to: 'profile#profile' , as: 'profile'
  get '/news', to: 'home#news' , as: 'news'
  get '/about', to: 'home#about' , as: 'about'
  get '/index', to: 'home#index' , as: 'home'

  post '/news', to: 'home#addnews' , as: 'addnews'
  post '/addUser/:id', to: 'home#addUsername' , as: 'addUsername'
  root to: "home#index"
  devise_for :user_devises
  devise_for :users, controllers: { sessions: 'user_devises/sessions' }

end

app/models/city.rb
class City < ActiveRecord::Base
  belongs_to :player
  belongs_to :group
end

app/models/group.rb
class Group < ActiveRecord::Base
  belongs_to :player
  has_one :city
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :follower, class_name: "user_devise"
  belongs_to :followed, class_name: "user_devise"
end

app/models/news.rb
class News < ActiveRecord::Base
end

app/models/player.rb
class Player < ActiveRecord::Base

  has_many :groups
  has_many :cities
end

app/models/religion.rb
class Religion < ActiveRecord::Base
end

app/models/unit.rb
class Unit < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :player
end

app/models/user_devise.rb
class UserDevise < ActiveRecord::Base
  has_one :player
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def news
    @news = News.all
  end
  def addnews
    @news = News.new
    @news.title = params[:title]
    @news.content = params[:contentNews]
    @news.image = params[:image]
    @news.save!
    redirect_to :back
  end

  def addUsername
    @myUser = UserDevise.find(params[:id])
    @myUser.update_attribute(:username, params[:newUsername])
    redirect_to :back
  end
  def about
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  def profile
  end
end

app/controllers/user_devises/confirmations_controller.rb
class UserDevises::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user_devises/omniauth_callbacks_controller.rb
class UserDevises::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user_devises/passwords_controller.rb
class UserDevises::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user_devises/registrations_controller.rb
class UserDevises::RegistrationsController < Devise::RegistrationsController
# before_action :configure_sign_up_params, only: [:create]
# before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user_devises/sessions_controller.rb
class UserDevises::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/user_devises/unlocks_controller.rb
class UserDevises::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/views/home/about.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PT - About</title>
</head>
<body>

  <div class="col-md-3"></div>
  <div class="title-border col-md-7">
    <div class="scll"><%=image_tag("TemeriaTitle.png", :class => "title")%></div>
  </div>
  <div class="side-bar col-md-2">
    <div class="scll2">
      <ul>
        <li><%= link_to 'Home' , home_path%></li>
        <li><%= link_to 'Profile' , profile_path%></li>
        <li><a href="#contact">Documentation</a></li>
        <li><%= link_to 'About' , about_path%></li>
        <li><%= link_to 'News' , news_path%></li>
        <% if user_devise_signed_in? %>
            <li>
              <%= link_to('Logout', destroy_user_devise_session_path, :method => :delete) %>
            </li>
        <% else %>
            <li>
              <%= link_to('Login', new_user_devise_session_path)  %>
            </li>
        <% end %>
      </ul>
    </div>
  </div>
  <div class="col-md-1"></div>
  <div class="game-container col-md-7">
    <div class="scll3">
      <h1>About us</h1>
      <hr>
      <h2 class="about-h2">Find us on Git Hub !</h2>
      <a href="https://github.com/erikmompean/ProjectTemeria"><%=image_tag("github.png", :class => "title")%></a>
      <h2 class="about-h2">Or...</h2>
      <h2 class="about-h2">On Facebook !</h2>
      <a href="https://www.facebook.com/erik.mompeanruiz"><%=image_tag("facebook.png", :class => "title")%></a>
    </div>
  </div>

</body>
</html>

app/views/home/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PT - HOME</title>
</head>
<body>
<div class="bg-img">
    <div class="col-md-3 col-sm-5"></div>
    <div class="title-border col-md-7 col-xs-12 col-sm-12">
      <div class="scll"><%=image_tag("TemeriaTitle.png", :class => "title")%></div>
    </div>
  <div class="side-bar col-md-2">
    <div class="scll2">
      <ul>
        <li><%= link_to 'Home' , home_path%></li>
        <li><%= link_to 'Profile' , profile_path%></li>
        <li><a href="#contact">Documentation</a></li>
        <li><%= link_to 'About' , about_path%></li>
        <li><%= link_to 'News' , news_path%></li>
        <% if user_devise_signed_in? %>
            <li>
              <%= link_to('Logout', destroy_user_devise_session_path, :method => :delete) %>
            </li>
        <% else %>
            <li>
              <%= link_to('Login', new_user_devise_session_path)  %>
            </li>
        <% end %>
      </ul>
    </div>
  </div>
  <div class="col-md-1"></div>
  <div class="game-container col-md-7">
    <div class="scll-game">

      <div class="row">
        <div class="col-md-12">
          <% if user_devise_signed_in? %>
              <%@myId = current_user_devise.id%>
              <p><%=UserDevise.find(@myId).id%></p>
              <p><%=@myId%></p>
            <%if UserDevise.find(@myId).username ==  "No name yet"%>
                <%= form_tag(addUsername_path(current_user_devise.id)) do %>

                    <%= label_tag 'Username', nil%>
                    <%= text_field_tag 'newUsername', nil, placeholder: 'introduce tu nombre de usuario', :required => true %>

                    <%= submit_tag "Añadir", class: 'btn btn-primary' %>
                <% end %>
            <%end%>

          <%end%>
          <% @users = UserDevise.all %>
          <% @users.each do |user| %>
              <%= user.email %>
              <%= user.username %><br/>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
</body>
</html>

app/views/home/news.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PT - News</title>
</head>
<body>

  <div class="col-md-3"></div>
  <div class="title-border col-md-7">
    <div class="scll"><%=image_tag("TemeriaTitle.png", :class => "title")%></div>
  </div>
  <div class="side-bar col-md-2">
    <div class="scll2">
      <ul>
        <li><%= link_to 'Home' , home_path%></li>
        <li><%= link_to 'Profile' , profile_path%></li>
        <li><a href="#contact">Documentation</a></li>
        <li><%= link_to 'About' , about_path%></li>
        <li><%= link_to 'News' , news_path%></li>
        <% if user_devise_signed_in? %>
            <li>
              <%= link_to('Logout', destroy_user_devise_session_path, :method => :delete) %>
            </li>
        <% else %>
            <li>
              <%= link_to('Login', new_user_devise_session_path)  %>
            </li>
        <% end %>
      </ul>
    </div>
  </div>
  <div class="col-md-1"></div>
  <div class="game-container col-md-7">
    <div class="scll3">
      <h1>NEWS</h1>
      <% @news.each do |n| %>
          <h2><%= n.title %></h2>
          <img class="blog-img" src='<%= n.image %>'>
          <p><%=raw sanitize(simple_format(n.content), :tags => %w(br p) ) %></p>
      <% end %>
      <h2>Project temeria Pre-Alfa</h2>
      <p>Greetings Temerians!
        We are proud and excited to announce that the latest update (1.3.3) for Project Temeria on PC/Mac/Linux is now live!   From swirling Sandstorms to brand new gear to the elusive and deadly Sand Shark, the 1.3.3 update brings the Deset Biome up to a whole new level!
      </p>

      <img class="blog-img" src="https://i.ytimg.com/vi/8UO8sdWiDB0/maxresdefault.jpg">
      <p>
        So, shake the sand out of your shoes and take a few minutes to check out the changelog below - and while you are there, don't forget to share your thoughts and feedback with the team so that we can continue to improve and evolve Project Temeria moving forward!
      </p>
      <hr>
      <h2>CHANGING OF THE GUARD​</h2>
      <p>Greetings Temerians!
        As this is a major milestone in the journey of Terraria on Console and Mobile, we took a step back and evaluated everything that we had currently going on as well as available resources. To that end, we are making a shift in the development teams moving forward. We thank Engine and Codeglue for all of their contributions to bringing Terraria to a wider community but we’ve made the decision to bring all development in-house under one roof with Pipeworks. So say a big thank you to them both, and a give a warm welcome to Pipeworks!
      </p>

      <img class="blog-img" src="http://vignette1.wikia.nocookie.net/witcher/images/a/aa/Loading_Trade_quarter_day.png">
      <p>
        Engine will remain on board until the final Old Gen Console Update is complete, while CodeGlue will remain on board until sometime in Q3, as they continue their work on stabilizing the mobile codebase. CodeGlue will also remain on board for any future 3DS updates.
      </p>

      <%= form_tag(addnews_path) do %>

          <%= label_tag 'Titulo', nil%>
          <%= text_field_tag 'title', nil, placeholder: 'introduce el titulo', :required => true %>
          <%= label_tag 'imagen', nil%>
          <%= text_field_tag 'image', nil, placeholder: 'introduce el titulo', :required => true %>
          <%= label_tag 'Descripcion del subforo', nil%>
          <%= text_area_tag 'contentNews', nil, rows: 5, cols: 1, class: 'contenido', placeholder: 'Aqui va el contenido...', :required => true %>

          <%= submit_tag "Añadir", class: 'btn btn-primary add-foro-btn' %>
      <% end %>
    </div>
  </div>
  <a href="#" id="back-to-top" title="Back to top"><%=image_tag("sword.png")%></a>
</body>
</html>